package ch.cidzoo.journalibs;

import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import android.app.Activity;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.location.Address;
import android.location.Criteria;
import android.location.Geocoder;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.support.v4.app.ListFragment;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.ListView;
import android.widget.SimpleCursorAdapter;
import android.widget.TextView;
import ch.cidzoo.journalibs.db.DaoMaster;
import ch.cidzoo.journalibs.db.DaoMaster.DevOpenHelper;
import ch.cidzoo.journalibs.db.DaoSession;
import ch.cidzoo.journalibs.db.IngredientDao;
import ch.cidzoo.journalibs.db.Meal;
import ch.cidzoo.journalibs.db.MealDao;

/**
 * A list fragment representing a list of Meals. This fragment
 * also supports tablet devices by allowing list items to be given an
 * 'activated' state upon selection. This helps indicate which item is
 * currently being viewed in a {@link MealDetailFragment}.
 * <p>
 * Activities containing this fragment MUST implement the {@link Callbacks}
 * interface.
 */
public class MealListFragment extends ListFragment {

	/**
	 * Get reference on the system Location manager
	 */
	LocationManager locationManager;

	/**
	 * Database stuff - generated by greenDAO
	 */
	private SQLiteDatabase db;
	private DaoMaster daoMaster;
	private DaoSession daoSession;
	private IngredientDao ingredientDao;
	private MealDao mealDao;
	private Cursor cursor;

	/**
	 * The serialization (saved instance state) Bundle key representing the
	 * activated item position. Only used on tablets.
	 */
	private static final String STATE_ACTIVATED_POSITION = "activated_position";

	/**
	 * The fragment's current callback object, which is notified of list item
	 * clicks.
	 */
	private Callbacks mCallbacks = sDummyCallbacks;

	/**
	 * The current activated item position. Only used on tablets.
	 */
	private int mActivatedPosition = ListView.INVALID_POSITION;

	/**
	 * A callback interface that all activities containing this fragment must
	 * implement. This mechanism allows activities to be notified of item
	 * selections.
	 */
	public interface Callbacks {
		/**
		 * Callback for when an item has been selected.
		 */
		public void onItemSelected(String id);
	}

	/**
	 * A dummy implementation of the {@link Callbacks} interface that does
	 * nothing. Used only when this fragment is not attached to an activity.
	 */
	private static Callbacks sDummyCallbacks = new Callbacks() {
		@Override
		public void onItemSelected(String id) {
		}
	};

	/**
	 * Mandatory empty constructor for the fragment manager to instantiate the
	 * fragment (e.g. upon screen orientation changes).
	 */
	public MealListFragment() {
	}

	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		// Get the location manager
		locationManager = (LocationManager) getActivity().getSystemService(Context.LOCATION_SERVICE);

		DevOpenHelper helper = new DaoMaster.DevOpenHelper(this.getActivity(), "meals_diary", null);
		db = helper.getWritableDatabase();
		helper.onUpgrade(db, db.getVersion(), db.getVersion()+1); //FIXME: devel
		daoMaster = new DaoMaster(db);
		daoSession = daoMaster.newSession();
		mealDao = daoSession.getMealDao();

		String dateColumn = MealDao.Properties.Date.columnName;
		String orderBy = dateColumn + " COLLATE LOCALIZED ASC";
		cursor = db.query(mealDao.getTablename(), mealDao.getAllColumns(), null, null, null, null, orderBy);

		SimpleCursorAdapter adapter = new SimpleCursorAdapter(
				this.getActivity(), 
				android.R.layout.simple_list_item_2, 
				cursor, 
				new String[] { dateColumn, MealDao.Properties.Location.columnName },
				new int[] { android.R.id.text1, android.R.id.text2 }, 
				SimpleCursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER);
		
		adapter.setViewBinder(new SimpleCursorAdapter.ViewBinder() {
			
			@Override
			public boolean setViewValue(View view, Cursor cursor, int columnIndex) {
				switch (view.getId()) {
				case android.R.id.text1:
					Log.i("setViewValue", cursor.getColumnName(columnIndex));
					String dateStr = new Date(cursor.getLong(columnIndex)).toString();
					((TextView) view).setText(dateStr);
					break;

				case android.R.id.text2:
					Log.i("setViewValue", cursor.getColumnName(columnIndex));
					((TextView) view).setText(cursor.getBlob(columnIndex).toString());
					break;
				}
				
				return true;
			}
		});

		setListAdapter(adapter);

		setHasOptionsMenu(true);
	}

	@Override
	public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
		inflater.inflate(R.menu.mainmenu, menu);
		super.onCreateOptionsMenu(menu, inflater);
	}

	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		Log.i("JournalIBS", "onOptionsItemSelected");

		switch (item.getItemId()) {
		case R.id.action_add:
			locationManager.requestSingleUpdate(LocationManager.NETWORK_PROVIDER, new LocationListener() {

				@Override
				public void onStatusChanged(String provider, int status, Bundle extras) {
					// TODO Auto-generated method stub

				}

				@Override
				public void onProviderEnabled(String provider) {
					// TODO Auto-generated method stub

				}

				@Override
				public void onProviderDisabled(String provider) {
					// TODO Auto-generated method stub

				}

				@Override
				public void onLocationChanged(Location location) {
					double lat = location.getLatitude();
					double lon = location.getLongitude();

					Log.i("onLocationChanged", "got a location update: lat=" + lat + " / lon=" + lon);

					Geocoder gc = new Geocoder(getActivity().getApplicationContext(), Locale.getDefault());
					try {
						List<Address> addresses = gc.getFromLocation(lat, lon, 1);
						Address adr = addresses.get(0);
						String buf = new String(adr.getCountryName() + ", " + adr.getLocality() + ", " + adr.getAddressLine(0));
						Meal meal = new Meal(null, new Date(), buf.getBytes());
						mealDao.insert(meal);
						cursor.requery();
					} catch (IOException e) {
						Log.i("onLocationChanged", "unknown location");
					}

				}
			}, null);

			
			break;
		}
		

		return super.onOptionsItemSelected(item);
	}

	@Override
	public void onViewCreated(View view, Bundle savedInstanceState) {
		super.onViewCreated(view, savedInstanceState);

		// Restore the previously serialized activated item position.
		if (savedInstanceState != null
				&& savedInstanceState.containsKey(STATE_ACTIVATED_POSITION)) {
			setActivatedPosition(savedInstanceState.getInt(STATE_ACTIVATED_POSITION));
		}
	}

	@Override
	public void onAttach(Activity activity) {
		super.onAttach(activity);

		// Activities containing this fragment must implement its callbacks.
		if (!(activity instanceof Callbacks)) {
			throw new IllegalStateException("Activity must implement fragment's callbacks.");
		}

		mCallbacks = (Callbacks) activity;
	}

	@Override
	public void onDetach() {
		super.onDetach();

		// Reset the active callbacks interface to the dummy implementation.
		mCallbacks = sDummyCallbacks;
	}

	@Override
	public void onListItemClick(ListView listView, View view, int position, long id) {
		super.onListItemClick(listView, view, position, id);

		// Notify the active callbacks interface (the activity, if the
		// fragment is attached to one) that an item has been selected.
		mCallbacks.onItemSelected( ((Meal) getListAdapter().getItem(position)).getId().toString() );
	}

	@Override
	public void onSaveInstanceState(Bundle outState) {
		super.onSaveInstanceState(outState);
		if (mActivatedPosition != ListView.INVALID_POSITION) {
			// Serialize and persist the activated item position.
			outState.putInt(STATE_ACTIVATED_POSITION, mActivatedPosition);
		}
	}

	/**
	 * Turns on activate-on-click mode. When this mode is on, list items will be
	 * given the 'activated' state when touched.
	 */
	public void setActivateOnItemClick(boolean activateOnItemClick) {
		// When setting CHOICE_MODE_SINGLE, ListView will automatically
		// give items the 'activated' state when touched.
		getListView().setChoiceMode(activateOnItemClick
				? ListView.CHOICE_MODE_SINGLE
						: ListView.CHOICE_MODE_NONE);
	}

	private void setActivatedPosition(int position) {
		if (position == ListView.INVALID_POSITION) {
			getListView().setItemChecked(mActivatedPosition, false);
		} else {
			getListView().setItemChecked(position, true);
		}

		mActivatedPosition = position;
	}   
}
