package ch.cidzoo.journalibs.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ch.cidzoo.journalibs.db.Ingredient;
import ch.cidzoo.journalibs.db.Meal;

import ch.cidzoo.journalibs.db.IngredientDao;
import ch.cidzoo.journalibs.db.MealDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ingredientDaoConfig;
    private final DaoConfig mealDaoConfig;

    private final IngredientDao ingredientDao;
    private final MealDao mealDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ingredientDaoConfig = daoConfigMap.get(IngredientDao.class).clone();
        ingredientDaoConfig.initIdentityScope(type);

        mealDaoConfig = daoConfigMap.get(MealDao.class).clone();
        mealDaoConfig.initIdentityScope(type);

        ingredientDao = new IngredientDao(ingredientDaoConfig, this);
        mealDao = new MealDao(mealDaoConfig, this);

        registerDao(Ingredient.class, ingredientDao);
        registerDao(Meal.class, mealDao);
    }
    
    public void clear() {
        ingredientDaoConfig.getIdentityScope().clear();
        mealDaoConfig.getIdentityScope().clear();
    }

    public IngredientDao getIngredientDao() {
        return ingredientDao;
    }

    public MealDao getMealDao() {
        return mealDao;
    }

}
